### PR TITLE
Fix copyright year: 2015 to 2016

### PR DESCRIPTION
**Pull request by McFanta**
Fixing this copyright year on pubishments section

### CODE REVIEW

**Comment by alexanderjoe** [comment]
Uhh, yeah this area shouldn't exist so I will not merge, I will just delete.

**Comment by McFanta** [comment]
Could you check a mail to the Override Network? I sent a mail because I am interested to become a developer :)! I can work on the website ;P! But I need to know what the team speak is so I can talk to other devs!

**Comment by alexanderjoe** [comment]
Teamspeak is ts.overridenetwork.net
We can talk about the email later :p

**Comment by McFanta** [comment]
Add me to staff interviews.

**Comment by McFanta** [comment]
@alexanderjoe I am on team speak now ;P! I hope my wifi will be stable now ;)! I am at my cottage ;P! Looking forward for this development team. Will work my best at the web! We can talk withn 30 min ;P! Cya!

**Comment by McFanta** [comment]
Wanna talk in staff interviews in team speak at 4 pm central european time? @alexanderjoe 
If I get accepted as developer, I can work at the website ;)! Looking forward to work with you!

Regards McFanta_

**Pull request closed without merging**
